### ISSUE TITLE
Transition duration not working in Chrome

### ISSUE THREAD

**Issue by balintlaczko** [vueform/slider#10]
Hello there, thanks for the awesome slider component! :)

I am trying to work with different transition durations when changing the slider value. It works as one would expect in Firefox, but there seems to be a problem in Chrome that I can't wrap my head around...
In short: _only_ the default 0.3s transition duration works. It partially reacts to custom durations, and both in case of `.slider-connect` and `.slider-origin` the transition starts with the speed I define, but then 0.3 seconds later it just jumps to the destination value. So it starts out correctly, then "breaks" the transition, and jumps.
The problem is not apparent with the default 0.3s transition-duration, but I even tried to overwrite that 0.3s (for example to 3s) in the module itself (both in default.css and default.scss), and then the issue becomes apparent the same way with any default slider...
Am I missing something here? Or is this some kind of Chrome bug? Any suggestions are welcome. :)

**Comment by adamberecz** [comment]
Closing this in absence of reproducible example. Feel free to reopen with a fiddle code.
