### ISSUE TITLE
TypeScript declaration file missing

### ISSUE THREAD

**Issue by oliv3** [vueform/slider#12]
Hi, I'm updating my Vue3 application to use TS. I get this error:

`TS7016: Could not find a declaration file for module '@vueform/slider'. '[...]/node_modules/@vueform/slider/dist/slider.js' implicitly has an 'any' type.
  Try npm i --save-dev @types/vueform__slider if it exists or add a new declaration (.d.ts) file containing "declare module '@vueform/slider';"`

`npm i --save-dev @types/vueform__slider` didn't find anything.

What can I do about this ? Thanks !

**Comment by boussadjra** [comment]
This project is built using only js, you could add the file `slider.d.ts` next to `shims-vue.d.ts` with the following content :

     declare module '@vueform/slider'

**Comment by oliv3** [comment]
I already tried that, but the warning/error was/is still present. Maybe a vscode/vetur issue ?

**Comment by boussadjra** [comment]
For me I just restarted the `npm run serve` command

**Comment by oliv3** [comment]
I also had to restart vscode, now the warning is gone.
