### ISSUE TITLE
Add "slider-focused" class when the component is focused

### ISSUE THREAD

**Issue by rosell-dk** [vueform/slider#13]
When a sleek look is wanted, one might want only to show the tooltip when working with the slider.
This is btw default behavior in [vue-slider-component](https://www.npmjs.com/package/vue-slider-component).

This can be achieved with styling like this: (when wrapped in a div with class "slider")
```
.slider .slider-tooltip {
  display: none;
}
.slider:hover .slider-tooltip,
.slider .slider-active .slider-tooltip {
  display: block;
}
```
However. It would also be desirable to have the tooltip show when the component is focused, so the ones that prefers working with keyboard instead of mouse can see what they are changing the value to.
How can this be achieved?

It would be great if your component added a "slider-focused" class when in focus!

Or alternatively, you could perhaps add an option that triggers the behavior I'm trying to achieve?

**Comment by adamberecz** [comment]
Added in `2.0.0` as well as `showTooltip` prop. Check it out.
