### ISSUE TITLE
Non semantic HTML id tag

### ISSUE THREAD

**Issue by markusand** [vueform/slider#14]
The div wrapper for the slider has a `slider` id. An HTML document cannot have more than one element with the same id, so this become unsemantic when including multiple sliders to a page.

**Comment by oliv3** [comment]
There is an `id` [prop](https://github.com/vueform/slider#basic-props) (which defaults to `slider`), maybe that's what you want to change ?

**Comment by markusand** [comment]
I absolutelly missed this prop, my bad.

However, I would default id to undefined (not have an id).

**Comment by adamberecz** [comment]
Change the id to `undefined` by default in `2.0.0` up.
