### ISSUE TITLE
Issues when using for audio player position

### ISSUE THREAD

**Issue by xorik** [vueform/slider#15]
Hi. I've created a small demo, where I've tried to use this component as progress bar for an audio player:
https://github.com/xorik/slide-player

So I found 2 issues:
1) When value is changed externally, the component anyways sends `update:modelValue` events. You can see it in dev tools
<img width="561" alt="Screen Shot 2021-06-09 at 00 35 34" src="https://user-images.githubusercontent.com/347044/121266329-9db09600-c8ba-11eb-8e36-7e58c41b290a.png">
So it makes player stuck on the same place.

2) I've tried to workaround it, by ignoring this event (with computed), it helped a bit, and it works perfectly in firefox, but in chrome the slider is shaking which is visually not nice.

Any suggestions how to fix it?

**Comment by adamberecz** [comment]
Fixed this in `2.0.0` - now it should not trigger `input` event when changing external data.
