### ISSUE TITLE
Change slider and tooltip color based on value

### ISSUE THREAD

**Issue by man0099** [vueform/slider#17]
Hey, thank you for creating this component! 

**Is there a way to set different _slider and tooltip_ color as the value changes? 1-10 is red, 11-20 is yellow, 20-30 is green and so on.** 

I have had a look at the documents and various other slider components but as a new Vue developer, this is seemingly hard. If possible could I get a guide on how to do this? I believe you will help me. Cheers!

**Comment by adamberecz** [comment]
Here: https://jsfiddle.net/tew79x2u/1/
