### ISSUE TITLE
Wrong file path in index.d.ts + TS build issues

### ISSUE THREAD

**Issue by staryja4** [vueform/slider#18]
https://github.com/vueform/slider/blob/1e491ba0205bb7de5b2d3dea9159b164ff64cf77/src/index.d.ts#L1 references to a wrong file ... it should be `./Slider`.

Also, Vue 3 has a problem during build with all vueform components because the types extend from Vue. The current workaround ... shims file in project's `src` folder:
```
declare module '@vueform/slider/dist/slider.js' {
   import { DefineComponent } from 'vue'
   const component: DefineComponent
   export default component
}
```
and import component as
```
import Slider from '@vueform/slider/dist/slider.js`
```
The same applies to toggle and multiselect.

**Comment by adamberecz** [comment]
Hi @staryja4 ! I'll update the `index.d.ts` in the next patch - thanks for reporting! Could you submit a PR with proper type definitions for `Slider.d.ts` that work with Vue 2 & 3?
