### ISSUE TITLE
Slider prevents scrolling on mobile.

### ISSUE THREAD

**Issue by thetarnav** [vueform/slider#20]
Hello
The slider appears to be preventing scrolling when touched on a mobile device. I understand that clicking to change value is part of the slider's normal behavior, but it doesn't seem to be a good user experience when the value is changed by mistake while scrolling.
Is there some known way to prevent that from happening?

https://user-images.githubusercontent.com/24491503/127738455-2028043b-e70c-43fc-bf74-378cf81002d5.mp4

**Comment by adamberecz** [comment]
I'm afraid this is just how noUiSlider works. What you can do is to play around with `behavior` property:
https://refreshless.com/nouislider/behaviour-option/

You can pass noUiSlider options directly from the Slider component via `options`:
``` html
<Slider :options="{ behavior: 'drag' }" ... />
```
