### ISSUE TITLE
Slider handle does not update position when a new position value is calculated after change event triggered by click or moving with arrows.

### ISSUE THREAD

**Issue by vladiso** [vueform/slider#22]
Hey, I am trying to send the slider handle back to a default position after the change event is triggered. After the change event is triggered the default position is computed and then set as the new position of the slider handle. This works fine when dragging the slider handle. However, when clicking on a random position on the slider bar or moving the slider handle with the arrows it doesn't seem to work anymore. I'm using v-model directive to pass the position of the slider. I verified the correct position to be sent whenever the event is triggered which is why I'm tempted to think it might be an internal issue. Has anybody come across this so far and is willing to share their input?

**Comment by adamberecz** [comment]
Wrapping the value update into a `nextTick` should solve the problem. You won't see the slider going to the clicked position and then back, in case you need that you might use `setTimeout` with the duration of the animation.
