### ISSUE TITLE
[Feature] Add "exactInput" option

### ISSUE THREAD

**Issue by blackjak231** [vueform/slider#25]
Hey !

I have a slider going from 100 000 up to 250 000 with a step of 100. Associated to the slider is an input in which the user can adjust the price. The issue i'm facing is that if the user types 123 456 for example, the value will automatically be rounded to the nearest step which is 123 500.

There is an option in NoUiSlider which allows the value to be set exactly but is not currently usable with the SLider component. Would it be possible to have it as a boolean option ? 

NoUiSlider related doc : https://refreshless.com/nouislider/slider-read-write/#section-setting)

Thanks in advance !

**Comment by adamberecz** [comment]
Can pass options to the noUiSlider directly via `options` prop. Also `slider` is a property of the `Slider` component which exposes the noUiSlider instance, so you might use its functions directly.
