### ISSUE TITLE
[Feature request] Lazy update

### ISSUE THREAD

**Issue by markusand** [vueform/slider#28]
IMHO an option to lazy update the slider value would be very valuable when changes trigger computational expensive actions. By lazy I mean that v-model values change when user release the mouse click once in the desired final value. 

I've been looking in docs, both this and noUiSlider, and couldn't find any reference to this option. Sorry if I missed.

**Comment by adamberecz** [comment]
Thanks for the suggestion @markusand! I've added `lazy` option in `2.0.8` and made it `true` by default.
