### ISSUE TITLE
Changing class prop breaks display

### ISSUE THREAD

**Issue by scottix** [vueform/slider#29]
I am trying to change the class in a vue way, so I can change the color based on certain input.

Example:
https://jsfiddle.net/afr80kpm/1/

I see this was requested in another issue https://github.com/vueform/slider/issues/17 , although I feel that is a very hacky way around it.

It would be better if I could set a computed property to the props and have it update automatically without having to worry about dom and such.

**Comment by adamberecz** [comment]
It is breaking the display, because you're overriding the container class of the Slider, which gets replaced by `nouislider` and probably Vue does not insert that to the vnode tree.

An easy (and I think even better) workaround is to wrap the slider to a div and set the computed class on that.
