### ISSUE TITLE
Using options prop breaks dragging

### ISSUE THREAD

**Issue by rickardw** [vueform/slider#32]
Hi,

If I use the :options prop on the slider (seems to occur no matter what option or even if it's empty) the dragging is broken. I can drag one step, but then the functionallity stops and I can't drag anymore.

Happens to me even if I just add :options="{}" in your examples etc.

Why does this happen and can it be fixed? Thanks for a great component otherwise!

**Comment by Edmaniak** [comment]
Hi, I have the same issue. Even the format prop breaks the component. Such a shame :(

**Comment by Bergrebell** [comment]
i have the same issue when trying to get it to work with vue3 and tailwind.

**Comment by adamberecz** [comment]
Now this should be fixed in `2.0.8`. Thanks for reporting the issue.

**Comment by Bergrebell** [comment]
thanks a lot! works like a charm in `2.0.8`. :)
