### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'classList')

### ISSUE THREAD

**Issue by faxunil** [vueform/slider#34]
Hi!

I couldn't exactly investigate when this problem is tiggered
in the error this is marked:
t.onblur=function(){V.value.focused.split(" ").forEach((function(t){A.value.classList.remove(t)}))},t.onfocus=function(){V.value.focused.split(" ").forEach((function(t){A.value.classList.add(t)}))}})),j.value=!0},q=function(){M.value.off(),M.value.destroy(),M.value=null},R=function(t,e){j.value=!1,q(),H()};return (0,vue__WEBPACK_IMPORTED_MODULE_0__.onMounted)(H

Im using this for a time slider, i convert the time to seconds.

Any Idea please?

**Comment by hyvyys** [comment]
I get the following error but only when deploying a lib I made with this slider onto the target site:

```
Uncaught TypeError: a is undefined
    _mouseCapture https://cincelaser.com/themes/panda/cache/v_167_a1ba98e327a5397b4d5b2b5a121a007c.js:1572
    e.widget/</h[t]</< https://cincelaser.com/themes/panda/cache/v_167_a1ba98e327a5397b4d5b2b5a121a007c.js:1572
    _mouseDown https://cincelaser.com/themes/panda/cache/v_167_a1ba98e327a5397b4d5b2b5a121a007c.js:1572
    e.widget/</h[t]</< https://cincelaser.com/themes/panda/cache/v_167_a1ba98e327a5397b4d5b2b5a121a007c.js:1572
    _mouseInit https://cincelaser.com/themes/panda/cache/v_167_a1ba98e327a5397b4d5b2b5a121a007c.js:1572
    dispatch https://cincelaser.com/themes/panda/cache/v_167_a1ba98e327a5397b4d5b2b5a121a007c.js:3
    handle https://cincelaser.com/themes/panda/cache/v_167_a1ba98e327a5397b4d5b2b5a121a007c.js:3
v_167_a1ba98
```

**Comment by adamberecz** [comment]
Closing in absence of reproducible example.

**Comment by J-Sek** [comment]
1. Open the page and click on the handle
2. Click browser [back] button

This means the component is going to unload itself when one of the parts has active focus.

![image](https://user-images.githubusercontent.com/20162853/161395193-2b07a8ea-7f90-4833-8681-58f74ea5d3f5.png)
