### ISSUE TITLE
Float values rounded to 2 decimals

### ISSUE THREAD

**Issue by myobusan** [vueform/slider#36]
I have range from 0 -> 0.0065433661231. The UI looks fine but when I fetch the value it shows either 0.00 or 0.01 (if slider is >= 0.005)

Is there a way to increase number of decimals?

I tried 
`format: {
    decimals: 6
}`

but it only changes decimals in the UI, while the actual value is rounded

**Comment by adamberecz** [comment]
It seems like `nouislider` is rounding up to 2 decimals by default. You can override this with **their** `format` option (that you can pass to **our** `options` object):

```vue
<template>
  <Slider :options="options" ...>
</template>

<script>
export default {
  return {
    data: () => ({
      options: {
        format: {
          to: v => v.toFixed(6),
          from: v => v
        }
      }
    })
  }
}
</script>

```
