### ISSUE TITLE
PostCSS loader exceptions coming from calc rules

### ISSUE THREAD

**Issue by andosteinmetz** [vueform/slider#37]
I encountered a series of build errors when I included `<style src="@vueform/slider/themes/default.css"></style>` in a Nuxtjs project using PostCSS loader. 

The exception was thrown by PostCSS loader, and coming from CSS rules like this one:
`right:calc(var(--slider-tooltip-arrow-size, 5px)*-2);`

I believe the issue is the `-` character next to another character without any whitespace to distinguish a negative number from subtraction:
https://developer.mozilla.org/en-US/docs/Web/CSS/calc()#notes

I was able to fix the issue by changing the above line and those similar to it like so:
`right:calc(var(--slider-tooltip-arrow-size, 5px) * -2)` to distinguish `-2` from  `- 2`.

I imagine this problem is introduced during minification?

**Comment by adamberecz** [comment]
I've put the negative multipliers into brackets, let's see if that solves the problem. Feel free to reopen if not and I'll look into further.
