### ISSUE TITLE
Slider handle position in not in correct

### ISSUE THREAD

**Issue by wolfx1998** [vueform/slider#39]
Hi, I am trying to build a slider component on https://message.dk/shop . We are setting the min and max value for the slider and the values seem to be updating correctly, at least when it comes to the numbers under the slider. 
The issue is in the thumb in the slider. The position of it is completely off. 
Looking into your demo I saw that transform: translate you are using is going to -1000% for the 0 position and mine goes up to 100%. As soon as I add one more 0 in dev tools, position is correct. 
Also this only happens in production, development version uses the correct -1000% value. 
Do you have any idea of why is there a difference in numbers?

Here are two screen shots of what happens before and after adding additional 0 to the calculation:

<img width="535" alt="before" src="https://user-images.githubusercontent.com/33655797/145182468-ed476e88-4fcb-4e91-8f22-cee22912bd26.PNG">
 
<img width="530" alt="after" src="https://user-images.githubusercontent.com/33655797/145182478-1ae6c392-f5d1-4abf-8f4b-2b4766d9e61c.PNG">

**Comment by wolfx1998** [comment]
So, to answer my own question, the issue I found was the version of the package.
We used package.json setup like this: "@vueform/slider": "^2.0.3" and that was producing the issue in the build.
Instead, I have removed the cap to use exactly 2.0.3 and it works properly

**Comment by adamberecz** [comment]
Hi @wolfx1998, remove `package-lock.json` (`yarn.lock`) and `node_modules` then reinstall it. It should be fine - if not, let me know! Make sure that if you're using custom css update that one too to the latest.
