### ISSUE TITLE
 WARN  @vueform/slider doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module 

### ISSUE THREAD

**Issue by andysay** [vueform/slider#41]
WARN  @vueform/slider doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.             11:55:29

**Comment by markusand** [comment]
Happened to me today as well after updating Vite and other dependencies.

**Comment by mchestnut** [comment]
Looks like the issue is that there is no default export in the declaration file.

In `src/index.d.ts`, try the following code:
```
import * as Slider from './Slider';
export default Slider;
```

**Comment by lacorde** [comment]
Same issue on a Nuxt 3 project.
@mchestnut fix works for me.
