### ISSUE TITLE
Error in tailwind.scss (using TailwindCSS v3 with Nuxt 2)

### ISSUE THREAD

**Issue by DamianGlowala** [vueform/slider#45]
![image](https://user-images.githubusercontent.com/48835293/152238186-be8e2530-a2ad-49eb-a091-a2d5d681aa4a.png)

![image](https://user-images.githubusercontent.com/48835293/152238218-989a91f1-d690-4eb8-a364-f9a6661bf650.png)

**Comment by dzcpy** [comment]
Same issue, have you fond a way to solve it?
