### ISSUE TITLE
Styling option

### ISSUE THREAD

**Issue by febfeb** [vueform/slider#5]
Hi,

Thank you for making this library.
Is there any option for stylings, like background or line thickness?
if my value < 50 then background color turns to red, if my value > 50 then background color turns to green.

**Comment by vesper8** [comment]
Seems like everything is easily customizable. I was able to achieve the look I wanted with this:

```
<style>
@import '~@vueform/slider/themes/default.css';

.slider-connect {
  @apply tw-bg-black;
}

.slider-base {
  @apply tw-bg-black;
}

.slider-handle {
  opacity: 0.9;
  background: #06B0DA;
  cursor: pointer;
}

.slider-handle:hover {
  background: #86e1f8;
}

.slider-base, .slider-connects {
    height: 4px;
    border-radius: 5px;
}
</style>
```

**Comment by adamberecz** [comment]
Now we have styling option @febfeb from `2.0.0`. Check out [CSS vars](https://github.com/vueform/slider#styling-with-css-vars) and [Tailwind support](https://github.com/vueform/slider#styling-with-tailwind-css).
