### ISSUE TITLE
Step property

### ISSUE THREAD

**Issue by beatriznbarroso** [vueform/slider#58]
Hello, 

How can I make the slider move in decimal points but specific decimal points like, for example, move 0.50 at a time?

**Comment by nowackipawel** [comment]
Steps is not working sometimes , even a step and values are declared as ints it returning some floats.
It looks strange when you have min:200, max:4500, step:50 and finally you get 2300.000000001

**Comment by adamberecz** [comment]
@beatriznbarroso here's now:

```js
const options = {
  step: 0.5,
  format: {
    decimals: 1,
  }
}
```

```vue
<Slider v-bind="options" />
```

@nowackipawel can't reproduce, probably already solved, if not feel free to open a new issue.
