### ISSUE TITLE
Error if use together with @vue/compat mode (Slider v-model must be a Number or Array)

### ISSUE THREAD

**Issue by leifmarcus** [vueform/slider#59]
When using the `Slider` together with `vite` and the `@vue/compat` package, the binding of the value model will always throw an error.

We created an [example on stackblitz](https://stackblitz.com/edit/vitejs-vite-9sgeyb) where the error happens. It seems like this is related to the vue compat package, as this error is only shown, when the compat mode is enabled.

**Comment by adamberecz** [comment]
The example no longer working. Feel free to reopen if the issue is still relevant.
