### ISSUE TITLE
Slider value does not update correctly when setting lazy option to false

### ISSUE THREAD

**Issue by JennyZeiser** [vueform/slider#60]
We are using a single Slider in Vue 3 with the lazy option set to `false`.

If we drag the slider to 0 (our minimum value) and keep moving the mouse to the left (outside of the visible slider bar) without releasing the mouse, then back to the right (re-entering the visible slider bar), the slider value does no longer update.

It works fine when the lazy option is set to `true`.

**Comment by israelhuss** [comment]
Same here!

**Comment by schneiderjan** [comment]
same

**Comment by adamberecz** [comment]
Fixed in `2.1.6`.
