### ISSUE TITLE
Threshold feature

### ISSUE THREAD

**Issue by jovanjay** [vueform/slider#64]
is there a way to have a threshold? where by  given min and max (1-100) and a threshold of 75 (where threshold is dynamic). It will basically prevent slider to go pass the given threshold (75) but will still be able to go down.

**Comment by adamberecz** [comment]
You can use noUiSlider's `limit` option:
https://refreshless.com/nouislider/slider-options/#section-limit

```js
<Slider :options="{ limit: 75 }"/>
```

This prevents the distance to be larger than 75. If you want the max to be 75 just set `max: 75`.
