### ISSUE TITLE
Long float being passed to the format function

### ISSUE THREAD

**Issue by Quezler** [vueform/slider#7]
My usecase is having a `min` of 1 and a `max` of 12 to select an inclusive month range which grabs the english name of the month from an array by key, but for some values it returns really long floats, like for this example: `€5.000000000000001`

https://jsfiddle.net/gjhdu6pL/

(of course i can and i will round it down on my end to fix my usecase, but i figured i let ya'll know about this one)

**Comment by dougfelton** [comment]
I had this same problem when setting format as a function.  The solution for me was to:

1) Set format as an object instead AND
2) Set the decimal property of the format object to a value of 0

**Comment by adamberecz** [comment]
That's unfortunately how it is. Updated the example: 
``` vue
<script>
  import Slider from '@vueform/slider'

  export default {
    components: { Slider },
    data: () => ({
      value: 20,
      format: function (value) {
        return `€${Math.round(value)}`
      }
    })
  }
</script>
```

Or as @dougfelton proposed: using format as an object does not require any tweaking.
