### ISSUE TITLE
Tooltip merging with low numbers

### ISSUE THREAD

**Issue by Quezler** [vueform/slider#8]
Not sure if this is a bug or if i am just misinterpreting how it works, but under roughly the same conditions as #7 the merging doesn't seem to work, here is it set to 30 and will merge only when its just 3 apart: https://jsfiddle.net/Lsm5rxyf/1/

![Screen Shot 2021-03-21 at 10 55 17](https://user-images.githubusercontent.com/3179271/111900629-f72fc400-8a33-11eb-9826-cf4c6bb4086b.png)

![Screen Shot 2021-03-21 at 10 56 10](https://user-images.githubusercontent.com/3179271/111900650-13cbfc00-8a34-11eb-8df1-47eab888aaf3.png)

**Comment by adamberecz** [comment]
Fixed in `2.0.0`.
