### ISSUE TITLE
Passing :disabled property has no effect

### ISSUE THREAD

**Issue by maegnes** [vueform/slider#9]
I'm currently trying to disable the slider under different circumstances. But adding the prop **:disabled** to the slider component has no effect on the slider. It is not disabled and can be adapted as before.

My code:

```js
// isPurchasePriceSliderDisabled is a computed property of my component (returns true or false)

<Slider
  v-if="maxValues.purchasePrice"
  v-model="state.sliders.purchasePriceSlider"
  :tooltips="false"
  :step="10000"
  :min="0"
  :max="maxValues.purchasePrice"
  :disabled="isPurchasePriceSliderDisabled"
  @change="sliderFilterChange($event, 'purchasePriceSlider');">
</Slider>
```

If i'm going to add the disabled property manually in my dev tools, everything works as expected.

Used version: 1.0.3

Kind regards
Magnus

**Comment by adamberecz** [comment]
Fixed in `1.0.4`
